### ISSUE TITLE
[Bug] Screenshot shown a route credit expiry transaction but the details is not reflected. User is confused about what has happen

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-frontend#384]
![image](https://user-images.githubusercontent.com/22762719/30108721-011b2048-9336-11e7-967e-a1ea75b12a5e.png)

**Comment by joelchoo** [comment]
Display when route pass expires is empty

**Comment by joelchoo** [comment]
Related to #485

**Comment by chuasweechin** [comment]
To be fixed under revamp UI view for transaction history
