### ISSUE TITLE
SocketIO module not found

### ISSUE THREAD

**Issue by haiyo** [datagovsg/beeline-frontend#399]
Got this issue when trying to run it via xcode. Seems like the bridging header can't be generated?

**Comment by LoneRifle** [comment]
Hello @haiyo, and thanks for getting in touch! Could you describe what you did that led you to the problem, including any console output that you may have seen? To our knowledge we've not had difficulties using xcode to run beeline-frontend

**Comment by haiyo** [comment]
Hi, what I did was just to open up the project in xcode and starting build and run. The build failed with the following error:

Unknown type name 'SocketIOClient' HCPLDPlugin.m

Most probably due to some build settings which I might have missed out setting to brigde swift socketio module to be use in objective-c?

**Comment by LoneRifle** [comment]
Did you run `npm install` and `npm run install-ios` prior to this?

**Comment by LoneRifle** [comment]
Closing owing to lack of response. Thanks again for getting in touch, and let us know if you have any further queries!
