### ISSUE TITLE
Cannot find module '../plugman/platforms/ios'

### ISSUE THREAD

**Issue by farouk** [datagovsg/beeline-frontend#405]
hello,

can i get help on this error please.

i ran - `npm run install-ios`

![image](https://user-images.githubusercontent.com/646265/31160223-78ed82b0-a901-11e7-8bb3-a4ccc80ef249.png)

**Comment by LoneRifle** [comment]
Hi, and thanks for getting in touch!

Which version of Cordova are you using? We suspect that you might be running into the issue described in nordnet/cordova-hot-code-push#295 , which affects Cordova 7.x . If this is the case, we'll update the readme to reflect the need for an earlier version of Cordova. Thanks for flagging this!

**Comment by farouk** [comment]
Correct, using Cordova version 7.*

![image](https://user-images.githubusercontent.com/646265/31262651-2c010c26-aa8f-11e7-9af0-194c8340c0f4.png)

**Comment by LoneRifle** [comment]
Okay. Could you downgrade to 6.5 and see what happens? I'll put the change into the README when I have the time.

**Comment by farouk** [comment]
cordova looks ok @ v6.5

but there's problem with the image:

![image](https://user-images.githubusercontent.com/646265/31268713-267ec3e4-aab0-11e7-9807-8365a5775ed1.png)

**Comment by farouk** [comment]
i solved the image issue by copying the 2 files below from an empty project.

now it builds correctly.

![image](https://user-images.githubusercontent.com/646265/31269311-7c1a607c-aab2-11e7-816e-a5bad46d53cc.png)

**Comment by LoneRifle** [comment]
Cool. I'll leave this open for now until we can look into resizing the images in `/resources`

**Comment by LoneRifle** [comment]
Resolved with be292a
