### ISSUE TITLE
Back button in crowdstart routes is not working as intended

### ISSUE THREAD

**Issue by joelchoo** [datagovsg/beeline-frontend#491]
In all routes, if a crowdstart route is selected and then the back button is pressed, the user is brought back to the crowdstart tab instead of the all routes tab.

**Comment by chuasweechin** [comment]
This is a expected behavior of the app that @xujing is aware about

**Comment by chuasweechin** [comment]
I would say to real need to solve it yet. We can hold it off till in the revamp.

**Comment by chuasweechin** [comment]
No longer valid as crowd start route page had been removed in revamped UI.
